# Generated by Django 5.0.14 on 2026-08-16 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenditureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('group', models.CharField(choices=[('Operational', 'Operational'), ('Salaries & Wages', 'Salaries & Wages'), ('Utilities', 'Utilities'), ('Transport', 'Transport'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], max_length=20)),
                ('recurring', models.BooleanField(default=False)),
                ('recurring_period', models.CharField(blank=True, choices=[('Monthly', 'Monthly'), ('Termly', 'Termly')], max_length=10)),
                ('expected_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'expenditure categories',
            },
        ),
        migrations.CreateModel(
            name='SchoolRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('unit', models.CharField(max_length=30)),
                ('quantity_required', models.PositiveIntegerField()),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('applies_to_all', models.BooleanField(default=False)),
                ('applies_to_level_groups', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenditureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField(help_text='UGX')),
                ('date', models.DateField()),
                ('paid_to', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(choices=[('One-off', 'One-off'), ('Recurring', 'Recurring')], max_length=10)),
                ('period', models.CharField(blank=True, help_text='Free text, e.g. "April 2025" or "Term 1 2025"', max_length=50)),
                ('status', models.CharField(choices=[('Cleared', 'Cleared'), ('Partial', 'Partial'), ('Unpaid', 'Unpaid'), ('Overpaid', 'Overpaid')], max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='finance.expenditurecategory')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField(help_text='UGX')),
                ('date', models.DateField()),
                ('method', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Mobile Money', 'Mobile Money')], max_length=15)),
                ('receipt_no', models.CharField(max_length=50, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='students.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_group', models.CharField(choices=[('Senior 1', 'Senior 1'), ('Senior 2', 'Senior 2'), ('Senior 3', 'Senior 3'), ('Senior 4', 'Senior 4'), ('Senior 5', 'Senior 5'), ('Senior 6', 'Senior 6')], max_length=10)),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('tuition', models.PositiveIntegerField(help_text='UGX')),
            ],
            options={
                'unique_together': {('level_group', 'term', 'year')},
            },
        ),
        migrations.CreateModel(
            name='FeeExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField(help_text='UGX')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='finance.feestructure')),
            ],
            options={
                'unique_together': {('fee_structure', 'name')},
            },
        ),
        migrations.CreateModel(
            name='IncomeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('School Fees', 'School Fees'), ('Director Funds', 'Director Funds'), ('Donation', 'Donation'), ('Other', 'Other')], max_length=20)),
                ('amount', models.PositiveIntegerField(help_text='UGX')),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('term', models.CharField(blank=True, choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=10)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('opted_extras', models.ManyToManyField(blank=True, related_name='opted_by', to='finance.feeextra')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_assignments', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'term', 'year')},
            },
        ),
        migrations.CreateModel(
            name='StudentRequirementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_brought', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='finance.schoolrequirement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_records', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'requirement')},
            },
        ),
    ]
