# Generated by Django 5.0.14 on 2026-10-01 09:01

import apps.finance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('students', '0002_alter_parentinfo_father_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feepayment',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AddField(
            model_name='feepayment',
            name='class_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='request_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='receipt_no',
            field=models.CharField(default=apps.finance.models.generate_receipt_number, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_payments', to='students.student'),
        ),
        migrations.CreateModel(
            name='StudentFeeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('class_name', models.CharField(max_length=100)),
                ('level_group', models.CharField(choices=[('Senior 1', 'Senior 1'), ('Senior 2', 'Senior 2'), ('Senior 3', 'Senior 3'), ('Senior 4', 'Senior 4'), ('Senior 5', 'Senior 5'), ('Senior 6', 'Senior 6')], max_length=10)),
                ('amount_due', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('School fees', 'School fees'), ('Opening balance', 'Opening balance')], max_length=15)),
                ('charge_details', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_accounts', to='students.student')),
            ],
            options={
                'ordering': ['year', 'term', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.feepayment')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.studentfeeaccount')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpeningBalanceEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('Charge', 'Charge'), ('Payment', 'Payment')], max_length=10)),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='finance.studentfeeaccount')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='studentfeeaccount',
            constraint=models.UniqueConstraint(fields=('student', 'term', 'year'), name='unique_student_fee_account'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='positive_payment_allocation'),
        ),
    ]
