# Generated by Django 5.0.14 on 2026-10-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_feepayment_options_feepayment_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='requires_reconciliation',
            field=models.BooleanField(default=False),
        ),
    ]
