# Generated by Django 5.0.14 on 2026-08-16 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('Beginning of Term', 'Beginning of Term'), ('Test', 'Test'), ('Midterm', 'Midterm'), ('Project', 'Project'), ('End of Term', 'End of Term')], max_length=20)),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('o_level_type', models.CharField(choices=[('Compulsory', 'Compulsory'), ('Optional', 'Optional'), ('N/A', 'N/A')], max_length=10)),
                ('a_level_type', models.CharField(choices=[('Compulsory', 'Compulsory'), ('Optional', 'Optional'), ('N/A', 'N/A')], max_length=10)),
                ('level', models.CharField(choices=[('O-Level', 'O-Level'), ('A-Level', 'A-Level'), ('Both', 'Both')], max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('students_enrolled', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportCardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('included_result_types', models.JSONField(default=list)),
            ],
            options={
                'unique_together': {('term', 'year')},
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('level_group', models.CharField(choices=[('Senior 1', 'Senior 1'), ('Senior 2', 'Senior 2'), ('Senior 3', 'Senior 3'), ('Senior 4', 'Senior 4'), ('Senior 5', 'Senior 5'), ('Senior 6', 'Senior 6')], max_length=10)),
                ('stream', models.CharField(help_text='e.g. "A"/"B" (O-Level) or "Science"/"Arts" (A-Level)', max_length=20)),
                ('level', models.CharField(choices=[('O-Level', 'O-Level'), ('A-Level', 'A-Level')], max_length=10)),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_of', to='staff.teacher')),
            ],
            options={
                'verbose_name_plural': 'school classes',
                'ordering': ['level_group', 'stream'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('head_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='staff.teacher')),
                ('subjects', models.ManyToManyField(blank=True, related_name='departments', to='academics.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Compulsory', 'Compulsory'), ('Optional', 'Optional')], max_length=10)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='academics.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='academics.subject')),
            ],
            options={
                'unique_together': {('school_class', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='SubjectPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=150)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='academics.subject')),
            ],
            options={
                'ordering': ['paper'],
                'unique_together': {('subject', 'paper')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papers', models.JSONField(blank=True, default=list)),
                ('class_subject_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.classsubjectassignment')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='staff.teacher')),
            ],
            options={
                'unique_together': {('class_subject_assignment', 'teacher')},
            },
        ),
    ]
