# Generated by Django 5.0.14 on 2026-10-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_resultwindow_unique_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('Sciences', 'Sciences'), ('Arts', 'Arts'), ('Languages', 'Languages'), ('Technical', 'Technical / vocational'), ('General', 'General / cross-cutting'), ('Unclassified', 'Unclassified')], default='Unclassified', max_length=15),
        ),
    ]
