# Generated by Django 5.0.14 on 2026-08-16 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('combination', models.CharField(blank=True, help_text='A-Level only, e.g. PCM/ICT', max_length=30)),
                ('performance', models.FloatField(default=0, help_text='Cached latest-term average; kept in sync by the results engine')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('enrollment_date', models.DateField()),
                ('photo_url', models.URLField(blank=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.schoolclass')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('guardian', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('alt_phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=100)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_info', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='TermRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('class_position', models.PositiveIntegerField(blank=True, null=True)),
                ('total_students', models.PositiveIntegerField(blank=True, null=True)),
                ('average', models.FloatField(blank=True, null=True)),
                ('class_teacher_comment', models.TextField(blank=True)),
                ('dos_comment', models.TextField(blank=True)),
                ('hm_comment', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_records', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'term', 'year')},
            },
        ),
        migrations.CreateModel(
            name='StudentAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=1)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StudentSubjectEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Compulsory', 'Compulsory'), ('Optional', 'Optional')], max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Dropped', 'Dropped'), ('Pending', 'Pending')], default='Active', max_length=10)),
                ('score', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=1)),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.subjectpaper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'unique_together': {('student', 'subject', 'paper')},
            },
        ),
        migrations.CreateModel(
            name='TermEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('level', models.CharField(choices=[('O-Level', 'O-Level'), ('A-Level', 'A-Level')], max_length=10)),
                ('combination', models.CharField(blank=True, max_length=30)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Enrolled', 'Enrolled'), ('Pending', 'Pending')], max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_enrollments', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'term', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TermSubjectMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('grade', models.CharField(max_length=1)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('term_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.termrecord')),
            ],
            options={
                'unique_together': {('term_record', 'subject')},
            },
        ),
    ]
