# Generated by Django 5.0.14 on 2026-08-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentinfo',
            name='father_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
