# Generated by Django 5.0.14 on 2026-10-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_parentinfo_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo_file',
            field=models.FileField(blank=True, upload_to='student-photos/'),
        ),
    ]
