# Generated by Django 5.0.14 on 2026-08-16 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('days', models.JSONField(default=list, help_text='e.g. ["Monday", "Tuesday", ...]')),
                ('rooms', models.JSONField(default=list, help_text='Room names')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('period_index', models.PositiveIntegerField()),
                ('paper', models.CharField(blank=True, max_length=20)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('is_break', models.BooleanField(default=False)),
                ('break_label', models.CharField(blank=True, max_length=100)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='timetable.timetableconfig')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.schoolclass')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TimetablePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Position within the day — matches TimetableSlot.period_index')),
                ('label', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_break', models.BooleanField(default=False)),
                ('break_label', models.CharField(blank=True, max_length=100)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='timetable.timetableconfig')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('config', 'order')},
            },
        ),
    ]
